// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type DeleteTodoInput struct {
	ID string `json:"id"`
}

type NewTodoInput struct {
	Title  string `json:"title"`
	UserID string `json:"userId"`
}

type NewUserInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}
