package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"

	"github.com/39TO/gockerql/graph"
	"github.com/39TO/gockerql/graph/model"
)

// Todos is the resolver for the todos field.
func (r *userResolver) Todos(ctx context.Context, obj *model.User) ([]*model.Todo, error) {
	todos, _ := r.ucTodo.FindTodosByUserId(obj.ID)
	todosModel := make([]*model.Todo, len(todos))
	for i, todo := range todos {
		todosModel[i] = &model.Todo{
			ID:    todo.Id,
			Title: todo.Title,
			Done:  todo.Done,
		}
	}
	return todosModel, nil
}

// User returns graph.UserResolver implementation.
func (r *Resolver) User() graph.UserResolver { return &userResolver{r} }

type userResolver struct{ *Resolver }
